name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.0.3
# homepage: https://github.com/andrey-ushakov/esc_pos_printer
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # esc_pos_utils: ^1.0.0
  esc_pos_utils:
    git:
      url: git@github.com:lucasralves/esc_pos_utils_null_safety.git
      ref: v1.0.0
    # path: ../esc_pos_utils_null_safety
  charset_converter: ^2.0.0
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
