name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 3.1.6
homepage: https://github.com/andrey-ushakov/esc_pos_printer
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  esc_pos_utils:
    git: git@github.com:lucasralves/esc_pos_utils_null_safety.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
